[package]
name = "smart-contracts"
version = "0.1.0"
edition = "2021"

[lib]
create-type = ["cdylib", "rlib"]

[dependencies]
near-sdk = "4.0.0"

[profile.release]
codegen-units = 1
opt-level = "z"
lto = true
debug = false
panic = "abort"
overflow-checks = true
